# Generated by Django 4.2.24 on 2026-04-01 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission_system', '0006_creprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='application',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of the successful payment', null=True, upload_to='payments/screenshots/'),
        ),
        migrations.AddField(
            model_name='application',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Google Pay Transaction Ref ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Verification', 'Pending Verification'), ('Success', 'Success'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=25),
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
