# Generated by Django 4.2.29 on 2026-04-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_system', '0007_remove_application_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_courses', to='admission_system.course')),
            ],
        ),
    ]
